User login process completed
BucknellSustainability/Flower pull request #277
Opened 2018-02-26 02:27 UTC by BenMatase

2018-02-26 16:15 UTC, BenMatase commented on backend/api.py
> +<<<<<<< HEAD
Solve this conflict that somehow got in

2018-02-26 16:16 UTC, BenMatase commented on backend/api.py
> +    cursor = conn.cursor()
Should this be once and keep alive or should get new cursor everytime?

2018-02-26 16:21 UTC, BenMatase commented on backend/api.py
> +    body = (EMAIL_HTML_START +
Clean this up

2018-02-26 16:22 UTC, BenMatase commented on backend/api.py
> +    sendEmail('energyhill@bucknell.edu',
Do the explicit param naming

2018-02-26 16:22 UTC, BenMatase commented on backend/api.py
> +    body = (EMAIL_HTML_START +
Clean up

2018-02-26 16:22 UTC, BenMatase commented on backend/api.py
> +    sendEmail('energyhill@bucknell.edu',
Explicity param naming to make more readable

2018-02-26 16:28 UTC, BenMatase commented on backend/api.py
> +    body = (EMAIL_HTML_START +
Also make it a good looking email

2018-02-26 16:28 UTC, BenMatase commented on web/control-panel/login.html
> +                window.location.replace("http://eg.bucknell.edu/~bdm015/Flower/web/requests/requestApproval.html");
Make this url more dynamic?

2018-02-26 16:28 UTC, BenMatase commented on web/control-panel/login.html
> +          xhr.open('POST', 'http://linuxremote1.bucknell.edu:5001/get-profile');
Make this url more dynamic?

2018-02-26 16:29 UTC, BenMatase commented on web/requests/approveUser.html
> +          xhr.open('POST', 'http://linuxremote1.bucknell.edu:5001/approve-user');
Url more dynamic?

2018-02-26 16:29 UTC, BenMatase commented on web/requests/requestApproval.html
> +      <h1>Looks like you don't have access to the dashboard.  If you think this is a mistake, click the button below.</h1>
Make this prettier in another task.  Probably later

2018-02-26 16:30 UTC, BenMatase commented on web/requests/requestApproval.html
> +      <h1>Looks like you don't have access to the dashboard.  If you think this is a mistake, click the button below.</h1>
Also make this actually a button once we get sessions

2018-02-26 16:30 UTC, BenMatase commented on web/requests/requestApproval.html
> +          xhr.open('POST', 'http://linuxremote1.bucknell.edu:5001/request-access');
More dynamic URL?

2018-02-26 19:51 UTC, BenMatase commented on backend/api.py
> +    cursor = conn.cursor()
According to the internet, we don't need to close cursors for mysqldb cursors.. so I'm not worrying about it

2018-02-26 19:59 UTC, BenMatase commented on web/control-panel/login.html
> +                window.location.replace("http://eg.bucknell.edu/~bdm015/Flower/web/requests/requestApproval.html");
Leaving for now, will talk to Marchiori as of issue #279

2018-02-27 03:39 UTC, DTV96Calibre requested changes
Error logging should be handled before we start using this code.

2018-02-27 03:39 UTC, DTV96Calibre commented on backend/alerts.py
> +        print("Error: unable to fecth data")
Fecth is a misspelling

2018-02-27 03:39 UTC, DTV96Calibre commented on backend/api.py
>  # TODO: need to commit after executing insert
There are a butt ton of todos mostly related to error logging. Maybe address these before we start needing to identify what's wrong.

2018-02-27 03:39 UTC, DTV96Calibre commented on backend/api.py
> +    except UserDeniedException as e:
This exception will be silenced without any indication that something went wrong.

2018-02-27 03:39 UTC, DTV96Calibre commented on backend/api.py
> +    except UserDeniedException as e:
This is repeated below

2018-02-27 03:39 UTC, DTV96Calibre commented on web/control-panel/login.html
> +          xhr.open('POST', 'http://linuxremote1.bucknell.edu:5001/get-profile');
We should have these deployment specific values stored in config files.

2018-02-27 20:12 UTC, DTV96Calibre approved these changes

2018-02-27 20:12 UTC, merged